### ISSUE TITLE
Tilecover with the same min and max zoom creates unpredictable results

### ISSUE THREAD

**Issue by tcql** [mapbox/tile-cover#73] opened 2016-11-02 15:33 UTC
![screen shot 2016-11-02 at 11 01 03](https://cloud.githubusercontent.com/assets/348805/19935264/c465a670-a0ef-11e6-8d7d-467e31e818ad.png)
*trying to cover the US with `min_zoom:7, max_zoom: 7` - no coastal tiles, and lots of scattered random ones*

![screen shot 2016-11-02 at 11 28 09](https://cloud.githubusercontent.com/assets/348805/19935281/d93a2fbc-a0ef-11e6-94f8-ba587ad538f9.png)
*if I generate tiles with `min_zoom: 6, max_zoom: 7` then use tilebelt to get the child-tiles for z6 tiles, I get what I was expecting*

Interestingly, both runs result in the same number of tiles, which suggests there's just some data flow issue where the coastal tiles get their coordinates scrambled up

**Comment by bkowshik** [comment] 2016-11-16 10:32
I came across a similar issue today with the following code snippet:

```js
// File: index.js
var feature = {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[77.3440933227539,13.239277104266526],[77.3440933227539,13.239611302005722],[77.34443664550781,13.239611302005722],[77.34443664550781,13.239277104266526],[77.3440933227539,13.239277104266526]]]},"properties":{}};
var tiles = tileCover.geojson(feature.geometry, {min_zoom: 25, max_zoom: 25});
console.log(JSON.stringify(tiles));
```
I ran the script and piped to [tippecanoe](https://github.com/mapbox/tippecanoe) and [mbview](https://github.com/mapbox/mbview).
```sh
node index.js | tippecanoe -pf -pk -fo tileset.mbtiles && mbview tileset.mbtiles -q
```

<img width="1273" alt="screen shot 2016-11-16 at 3 50 22 pm" src="https://cloud.githubusercontent.com/assets/2899501/20343679/61630ad2-ac15-11e6-823c-36d18a0d2600.png">
*Staggered tiles viewed with [mbview](https://github.com/mapbox/mbview)*

<img width="1275" alt="screen shot 2016-11-16 at 4 01 09 pm" src="https://cloud.githubusercontent.com/assets/2899501/20343807/f621befc-ac15-11e6-80b1-b7fc04b26738.png">
*Close up view of staggered tiles*

**Comment by bkowshik** [comment] 2016-11-16 11:27
Also, I have seen the following behaviour on a couple of occasions. Basically, things are great except a few extra projection tiles somewhere around the corners of the feature that is tile-covered.

<img width="1275" alt="screen shot 2016-11-16 at 4 51 14 pm" src="https://cloud.githubusercontent.com/assets/2899501/20345437/33195f5c-ac1d-11e6-8130-8bad6c64a391.png">
*A z7 tile covered by z15 tiles*

<img width="1273" alt="screen shot 2016-11-16 at 4 51 37 pm" src="https://cloud.githubusercontent.com/assets/2899501/20345438/331a9da4-ac1d-11e6-9cbc-959f97fd2348.png">
*An extra tile on the top-left corner*

**Comment by bkowshik** [comment] 2016-11-22 18:30
Added a fixture and a failing test case with: https://github.com/mapbox/tile-cover/commit/a8fdfe57ca73383579b3aa5af8d9e577637e2980. The idea behind the fixture is:
1. When you take a `z20` tile as a feature
2. And `tile-cover` it with `min_zoom` and `max_zoom` limits of `20`
3. You should get the same feature as the tile

I am not sure if this fixture is helpful in creating a fix, but I am documenting it for reference.

---

cc: @tcql @mourner

**Comment by mourner** [comment] 2016-11-23 17:13
@bkowshik I think this can be an expected output — it may return adjacent tiles because the tile coordinate in mercator is unprojected to latitude/longitude bbox, which is subject to floating point precision errors, and then tiles that had a border exactly matching a tile side can start overlapping it slightly.

However, the cases in the first two comments look like serious bugs.

**Comment by mourner** [comment] 2016-11-28 15:35
@bkowshik It looks like https://github.com/mapbox/tile-cover/issues/73#issuecomment-260911228 is different from the original issue, and `tile-cover` generates the tiles properly but `tippecanoe` somehow rounds the coordinates because they're so tiny (cc @ericfischer could this be the case?). However, I don't think you should ever use a zoom as high as z25 — it translates to about 30-50cm width for a single tile.

**Comment by mourner** [comment] 2016-11-28 15:40
@tcql I can't reproduce the original issue with the following script — everything looks good:

```js
var tileCover = require('./');
var geojson = require('./test/fixtures/world/USA.geo.json');
var tiles = tileCover.geojson(geojson.features[0].geometry, {min_zoom: 7, max_zoom: 7});
console.log(JSON.stringify(tiles));
```

```bash
node debug.js | geojsonio
```

Can you set up a broken test case?

**Comment by ericfischer** [comment] 2016-11-28 18:08
@mourner Yes, it looks like the misaligned grid is probably from Tippecanoe tiny polygon reduction and could be eliminated with `--no-tiny-polygon-reduction`, at the cost of probably making the low zooms not work at all. I don't think this could explain the case of the one extra stray tile at the top left, but I'll try some tests and find out.

**Comment by mourner** [comment] 2016-12-14 11:50
@tcql I have to close this as not reproducible on the tile-cover side. Please feel free to reopen after we have a reproducible test case.

**Closed by mourner** 2016-12-14 11:50 UTC
Labels: bug
